name: pymrio_dev
channels: 
  - conda-forge
  - anaconda
  - defaults
dependencies: 
  # core
  - pandas >= 1.5
  - requests >= 2.18
  - xlrd > 1.1.0 
  - openpyxl >= 3.0.6
  - docutils >= 0.14
  # testing and developing
  - pdbpp
  - country_converter >= 0.7.7
  - pytest >= 5.4.3
  - isort >= 5.6.0
  - pytest-black
  - nbval
  - black >= 22.8
  - ipython
  - jupyterlab=3
  - jupytext
  - coveralls
  - pynvim
  - sphinx >= 1.6.4
  - sphinx_rtd_theme >= 0.2.4
  - ipykernel
  - nbsphinx
